### PR TITLE
Woriking Jakarta app

### PR DESCRIPTION
**Pull request by tommaso-borgato**
Hi, I would like to target branch jakartaee, not master

### CODE REVIEW

**Comment by tommaso-borgato** [comment]
@jfdenise I would like to target a new branch `jakartaee`

**Comment by jfdenise** [comment]
@bparees is owning this project. having a jakarta branch would be a good idea.

**Comment by bparees** [comment]
unfortunately i'm not really involved in this any more, but i'm not sure who a better owner would be.

That said, what is the intent of the new branch?  This repo is referenced (as i recall) from some of our sample content for the wildfly builder image.  Do you intent to publish samples that would point to the new branch?  Or some other way of referring people to it?

It might make more sense to just fork the repo and maintain it in another org that's more closely tied to jboss or wildfly, or whatever product/project you're intending to reference the sample from.

**Comment by tommaso-borgato** [comment]
@bparees recently, some of the "javax." namespace classes were migrated to the "jakarta." namespace (see e.g. https://blogs.oracle.com/javamagazine/post/transition-from-java-ee-to-jakarta-ee); anyone who, at present, wants to play with the latest java apis would benefit from this jakarta branch; these apis will ultimately replace the old ones

**Comment by bparees** [comment]
i've created the branch: https://github.com/openshift/openshift-jee-sample/tree/jakartaee

move your PR to there and i'll merge it

**Comment by tommaso-borgato** [comment]
> i've created the branch: https://github.com/openshift/openshift-jee-sample/tree/jakartaee
> 
> move your PR to there and i'll merge it

https://github.com/openshift/openshift-jee-sample/pull/29

**Pull request closed without merging**
